stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw/train.csv
      - data/raw/test.csv
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim/train.csv
      - data/interim/test.csv
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/interim/train.csv
      - data/interim/test.csv
    params:
      - feature_engineering.max_features
    outs:
      - data/processed/train_tfidf.csv
      - data/processed/test_tfidf.csv
  model_training:
    cmd: python src/models/model_building.py
    deps:
      - src/models/model_building.py
      - data/processed/train_tfidf.csv
      - data/processed/test_tfidf.csv
    params:
      - model_building.n_estimators
      - model_building.learning_rate
    outs:
      - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_Evaluation.py
    deps:
      - src/models/model_Evaluation.py
      - models/model.pkl
    outs:
      - reports/metrics.json