name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m nltk.downloader wordnet
          python -m nltk.downloader stopwords
      - name: Start MLflow Server
        run: |
          mlflow server --host 127.0.0.1 --port 5000 --backend-store-uri sqlite:///mlflow.db &
          sleep 5 # Give the server a moment to start
      - name: run Pipeline
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          dvc repro